# version: '3'
# services:
#   docsim:
#     image: docsim-image
#     build:
#       context: .
#       dockerfile: Dockerfile-docsim
#     container_name: docsim
#     restart: always
#     volumes:
#       - key-volume:/docsim/server/deploy/ssl
#   nginx:
#     image: nginx:latest
#     restart: always
#     volumes:
#       - ./server/deploy/nginx.conf:/etc/nginx/nginx.conf
#       - key-volume:/etc/nginx
#       # - ./server/deploy/ssl/server.crt:/etc/nginx/server.crt
#       # - ./server/deploy/ssl/server.key:/etc/nginx/server.key
#     ports:
#       - 8080:80
#       - 7777:443
#     depends_on:
#       - docsim
# volumes:
#   key-volume:

version: '3'
services:
  docsim:
    image: docsim-image
    build:
      context: .
      dockerfile: Dockerfile-docsim
    container_name: docsim
    restart: always
  nginx:
    image: nginx-docsim-image
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx-docsim
    restart: always
    ports:
      - 8010:80
      - 8011:443
    depends_on:
      - docsim